"""empty message

Revision ID: 7b60404ab471
Revises: 80a18af6cabc
Create Date: 2025-03-19 19:27:25.204853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b60404ab471'
down_revision = '80a18af6cabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'upload_arquivo', ['foto_perfil_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('foto_perfil_id')

    # ### end Alembic commands ###
