"""empty message

Revision ID: 80a18af6cabc
Revises: d74d628da19b
Create Date: 2025-03-19 19:11:21.132858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a18af6cabc'
down_revision = 'd74d628da19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_arquivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('caminho', sa.String(length=100), nullable=True),
    sa.Column('extensao', sa.String(length=100), nullable=True),
    sa.Column('tamanho', sa.String(length=100), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_arquivo')
    # ### end Alembic commands ###
